export const rulesData = [
  {
    id: "specific_collection",
    name: "Specific Collection",
    type: "collection",
    operators: ["contains_any", "is_not"],
    priority: 1,
    mutually_exclusive_with: ["specific_product"],
    value_type: "multi_select",
    multi_select_options: ["Automation", "Dress", "Collection"],
  },
  {
    id: "specific_product",
    name: "Specific Product",
    type: "product",
    operators: ["equals_any", "contains_any", "is_not"],
    priority: 2,
    mutually_exclusive_with: ["specific_collection"],
    value_type: "multi_select",
    multi_select_options: ["Automation", "Dress", "Collection"],
  },
  {
    id: "product_tags",
    name: "Product Tags",
    type: "tag",
    operators: ["contains_any", "is_not"],
    priority: 3,
    value_type: "multi_select",
    multi_select_options: ["Automation", "Dress", "Collection"],
  },
  {
    id: "product_subscribed",
    name: "Product Subscribed",
    type: "subscription",
    operators: [],
    priority: 4,
    value_type: "boolean",
  },
  {
    id: "specific_discount_codes",
    name: "Specific Discount Codes",
    type: "discount_code",
    operators: [],
    priority: 5,
    value_type: "text",
  },
  {
    id: "cart_value_range",
    name: "Cart Value Range",
    type: "cart_value",
    operators: ["is_equal_or_greater_than", "is_between", "is_less_than"],
    priority: 6,
    value_type: "numeric_range",
  },
];
